export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const ADD_SHOW = 'ADD_SHOW';
export const ADD_LIKE = 'ADD_LIKE';
export const SELECT_SHOW = 'SELECT_SHOW';
export const DESELECT_SHOW = 'DESELECT_SHOW';
export const SET_METRICS = "SET_METRICS";

export const ADD_FORM_INPUT_FIELD = 'ADD_FORM_INPUT_FIELD';
export const CHANGE_FORM_INPUT_VALUE = 'CHANGE_FORM_INPUT_VALUE';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const UPDATE_AUTH ='UPDATE_AUTH';
export const UPDATE_LOAD = 'UPDATE_LOAD';
export const DISPLAY_SIGNIN = 'DISPLAY_SIGNIN';